services:
  postgres:
    image: postgres:15-alpine
    container_name: cinema-postgres
    environment:
      POSTGRES_DB: cinemadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Student_1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  cinema-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: cinema-app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cinemadb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Student_1234
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres-data: